name: Deploy Docker Image to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - codebase/rdicidr-0.1.0/**

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Cache
        uses: docker/build-push-action@v3
        with:
          context: ./codebase/rdicidr-0.1.0
          file: ./codebase/rdicidr-0.1.0/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version and push tag
        id: semantic-version
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WITH_V: false

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./codebase/rdicidr-0.1.0
          file: ./codebase/rdicidr-0.1.0/Dockerfile
          push: true
          tags: hachikoapp/nginx-app:${{ steps.semantic-version.outputs.new_tag }}

